---

- name: create vpn and config strongswan
  hosts: localhost
  gather_facts: False
  pre_tasks:
    - name: get external ip address
      ipify_facts:
    - set_fact: 
        external_ip: "{{ ipify_public_ip }}"
    - set_fact: 
        aws_state: absent

  roles:
    - terraform
